# Generated by Django 4.1.2 on 2022-12-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballlingo',
            name='lingoid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
